### ISSUE TITLE
TBT_ROOT define deocumentation

### ISSUE THREAD

**Issue by canyondust** [osy86/ThunderboltReset#3]
Hi! Forgive my ignorance, where is TBT_ROOT defined / edited? 
Is the idea just to find/replace TBT_ROOT with \_SB_.PCI0.RP05.PXSX throughout the .asl file?

Edit: In the makefile itself?

**Comment by osy** [comment]
Example: https://github.com/osy86/ThunderboltReset/blob/master/ThunderboltNative/SSDT-TbtOnPCH-NUC-Hades-Canyon.asl#L7-L12
